SET LIN 500 PAGES 10000 VERIFY OFF
COL STARTING_TIME FOR A19
COL COMPLETION_TIME FOR A22
COL HANDLE FOR A24
COL TIME_TAKEN_DISPLAY FOR A10
COL HOURS FOR A10
COL SIZE_GB FOR 999,999
COL FIRST_SEQ FOR 999999999
COL LAST_SEQ FOR 9999999999
COL FIRST_SCN FOR 999999999999999
COL LAST_SCN FOR 999999999999999
COL LAST_TIME FOR A24
col CHECKPOINT_CHANGE for a20
COMP COUNT LABEL 'TPIECE#:' -
 MAX LABEL 'MAXPS-G:' -
 SUM LABEL 'TSIZE_G:' OF SIZE_GB ON BACKUP_TYPE FOR A20
BREAK ON BACKUP_TYPE SKIP 2
/* Author: Majid Shabani */
SELECT DECODE(S.BACKUP_TYPE,'D','FULL','L','ARCHBKP','I','DBINC')BACKUP_TYPE,
       TO_CHAR(S.START_TIME,'DD/MM/YY DY HH24:MI')STARTING_TIME,
       TO_CHAR(S.COMPLETION_TIME,'DD/MM/YY DY HH24:MI:SS')COMPLETION_TIME,
       S.TIME_TAKEN_DISPLAY, ROUND(P.BYTES/POWER(1024,3))SIZE_GB,
       P.HANDLE, COUNT(*) FILE#, THREAD#,
       MIN(A.SEQUENCE#) FIRST_SEQ, MAX(A.SEQUENCE#) LAST_SEQ,
       MIN(A.NEXT_CHANGE#)FIRST_SCN, MAX(A.NEXT_CHANGE#)LAST_SCN,
       TO_CHAR(MAX(A.NEXT_TIME),'YYYY-MM-DD DY HH24:MI:SS')LAST_TIME,
       MAX(C.CHECKPOINT_CHANGE#) ||'' CHECKPOINT_CHANGE
FROM RC_BACKUP_SET_DETAILS S, RC_BACKUP_PIECE P,
     RC_BACKUP_DATAFILE BD, RC_BACKUP_ARCHIVELOG_DETAILS A,
     RC_BACKUP_CONTROLFILE_DETAILS C
WHERE S.BS_KEY = P.BS_KEY
  AND BD.SET_STAMP (+)= P.SET_STAMP
  AND BD.SET_COUNT (+)= P.SET_COUNT
  AND A.btype_key(+) = P.BS_KEY
  AND C.ID1 (+)= P.SET_STAMP
  AND C.ID2 (+)= P.SET_COUNT
  AND C.BTYPE (+)= 'BACKUPSET'
  AND UPPER(S.DB_NAME)=UPPER('&1')
  AND S.SESSION_KEY=&2
GROUP BY DECODE(S.BACKUP_TYPE,'D','FULL','L','ARCHBKP','I','DBINC'),
      TO_CHAR(S.START_TIME,'DD/MM/YY DY HH24:MI'),
      TO_CHAR(S.COMPLETION_TIME,'DD/MM/YY DY HH24:MI:SS'),
      S.TIME_TAKEN_DISPLAY, S.ORIGINAL_INPUT_BYTES_DISPLAY,
      S.OUTPUT_BYTES_DISPLAY , P.HANDLE, THREAD#, P.BYTES
ORDER BY STARTING_TIME, MAX(A.NEXT_TIME), LAST_SEQ;
CLEAR BREAK;
CLEAR COMP;
SET VERIFY ON;
PAUSE
