SET LIN 500 PAGES 50 VERIFY OFF
COL HANDLE FOR A25
COL NAME FOR A65
COL TABLESPACE_NAME FOR A25
COL TS# FOR 9999
COL HOURS FOR A10
COL SPFILE_SIZE FOR A20
/* Author: Majid Shabani */
SELECT S.DB_NAME, S.DB_KEY, P.HANDLE, 
       DECODE(P.BACKUP_TYPE,'D','FULL','L','ARCHBKP','I','DBINC')BACKUP_TYPE,
       TO_CHAR(P.START_TIME,'YYYY-MM-DD HH24:MI')START_TIME,
       TO_CHAR(P.COMPLETION_TIME,'DD/MM/YY HH24:MI')COMPLETION_TIME,
       ROUND(P.BYTES/1024/1024) PIECE_SIZE_MB, TIME_TAKEN_DISPLAY HOURS,
       ORIGINAL_INPRATE_BYTES_DISPLAY IN_SPEED, OUTPUT_RATE_BYTES_DISPLAY OUT_SPEED, FILESIZE_DISPLAY SPFILE_SIZE, 
	   TO_CHAR(MODIFICATION_TIME,'YYYY-MM-DDHH24:MI:SS')MODIFICATION_TIME
FROM RC_BACKUP_SET_DETAILS S, RC_BACKUP_PIECE P, RC_BACKUP_SPFILE_DETAILS SP
WHERE S.BS_KEY = P.BS_KEY
  AND SP.SET_STAMP = P.SET_STAMP
  AND SP.SET_COUNT = P.SET_COUNT
  AND UPPER(S.DB_NAME)= UPPER('&1')
  AND (S.SESSION_KEY = &2 OR P.HANDLE = '&3');
SET VERIFY ON
