SET LIN 500 PAGES 50
COL HANDLE FOR A12
COL NAME FOR A65
COL TABLESPACE_NAME FOR A25
COL TS# FOR 9999
COL HOURS FOR A10
col IN_SPEED for a10
col OUT_SPEED for a10
/* Author: Majid Shabani */
SELECT S.DB_NAME, S.DB_KEY, P.HANDLE, D.TS#, D.TABLESPACE_NAME, D.FILE#, D.NAME, ROUND(D.BYTES/1024/1024/1024) FILE_SIZE_GB,
DECODE(P.BACKUP_TYPE,'D','FULL','L','ARCHBKP','I','DBINC')BACKUP_TYPE,
TO_CHAR(P.START_TIME,'DD/MM/YY HH24:MI')START_TIME, 
TO_CHAR(P.COMPLETION_TIME,'DD/MM/YY HH24:MI')COMPLETION_TIME, 
ROUND(P.BYTES/1024/1024/1024) PIECE_SIZE_GB, TIME_TAKEN_DISPLAY HOURS, 
ORIGINAL_INPRATE_BYTES_DISPLAY IN_SPEED, OUTPUT_RATE_BYTES_DISPLAY OUT_SPEED,
COUNT(*) OVER (PARTITION BY P.HANDLE) NO_FILE_IN_PIECE
,COUNT(DISTINCT P.HANDLE) OVER() PIECE_NO
FROM
RMAN.RC_BACKUP_SET_DETAILS S,
RMAN.RC_BACKUP_PIECE P,
RMAN.RC_BACKUP_DATAFILE BD,
RMAN.RC_DATAFILE D
WHERE S.BS_KEY = P.BS_KEY
  AND S.DB_KEY = D.DB_KEY
  AND BD.SET_STAMP = P.SET_STAMP
  AND BD.SET_COUNT = P.SET_COUNT
  AND BD.FILE# = D.FILE#
  AND UPPER(S.DB_NAME)= UPPER('&1')
  AND SESSION_KEY = &2 AND (P.HANDLE = '&3' OR DECODE('&3','null',1,0)=1 ) and (D.FILE# IN (&4) OR DECODE(&4,null,1,0)=1)
ORDER BY P.HANDLE, FILE#;
