SET LIN 500 PAGES 200 VERIFY OFF
COL SCRIPT_NAME FOR A23
COL SCRIPT_BODY FOR A120
BREAK ON SCRIPT_NAME SKIP 2
/* Author: Majid Shabani */
SELECT NAME DBNAME, D.DB_KEY, DBID, SCRIPT_NAME, LINE, TEXT SCRIPT_BODY
FROM RMAN.RC_DATABASE D, RC_STORED_SCRIPT_LINE S
WHERE D.DB_KEY = S.DB_KEY
AND UPPER(NAME) = UPPER('&1')
ORDER BY SCRIPT_NAME, LINE;
CLEAR BREAK
SET VERIFY ON
