SET LIN 500
COL NAME FOR A30
COL SID FOR 99999
COL VAL_GB FOR 999,999,999,999,999
COMPUTE SUM OF VAL_GB ON REPORT
BREAK ON REPORT
/* Author: Majid Shabani */
SELECT S.SID, N.NAME, ROUND(S.VALUE/1024/1024/1024,2) VAL_GB 
FROM V$SESSTAT S, V$STATNAME N, V$SESSION SS
WHERE S.STATISTIC# = N.STATISTIC#
  AND S.SID = SS.SID
  AND CLIENT_INFO LIKE 'rman%'
  AND NAME = 'physical write total bytes'
ORDER BY SID, NAME, VAL_GB DESC;
CLEAR BREAK
