PROMPT
PROMPT READ WRITE PERFORMED BY ALL CHANNELS
PROMPT
COL NAME FOR A30
COL SID FOR 99999
COL VAL_GB FOR 999,999,999,999,999
/* Author: Majid Shabani */
SELECT N.NAME, ROUND(SUM(S.VALUE)/POWER(1024,3),2) VAL_GB 
FROM V$SESSTAT S, V$STATNAME N, V$SESSION SS
WHERE S.STATISTIC# = N.STATISTIC#
  AND S.SID = SS.SID
  AND CLIENT_INFO LIKE 'rman%'
  AND NAME = 'physical write total bytes'
GROUP BY N.NAME
ORDER BY NAME, VAL_GB DESC;
